# Generated by Django 5.1.3 on 2025-01-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image_chapter_lesson_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
