# Generated by Django 5.1.3 on 2025-01-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_task_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='course.file'),
        ),
    ]
