# Generated by Django 5.1.3 on 2025-01-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_session_course_session_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='course.lesson'),
        ),
    ]
