# Generated by Django 5.1.3 on 2025-01-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_session_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='course.course'),
        ),
    ]
