# Generated by Django 5.1.3 on 2025-01-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_rate_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='course.course'),
        ),
    ]
