# Generated by Django 5.1.3 on 2025-01-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_session_end_date_alter_session_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
