# Generated by Django 5.1.3 on 2025-01-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_course_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='excerpt',
        ),
    ]
