# Generated by Django 5.1.3 on 2025-01-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_course_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
