# Generated by Django 5.1.3 on 2025-01-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_course_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='excerpt',
            field=models.TextField(),
        ),
    ]
