# Generated by Django 5.1.3 on 2025-02-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_taskstatus_task_deadline_task_difficulty_taskanswer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskStatus',
            new_name='AnswerStatus',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='course.answerstatus'),
        ),
    ]
