# Generated by Django 5.1.3 on 2025-09-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_rename_taskstatus_answerstatus_remove_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
