# Generated by Django 4.2.24 on 2025-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_lesson_is_published_lesson_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True, help_text='لینک ویدیو درس', null=True),
        ),
    ]
