# Generated by Django 4.2.24 on 2025-09-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_lesson_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='شماره')),
                ('cluster', models.CharField(max_length=200, verbose_name='خوشه')),
                ('group_name', models.CharField(max_length=200, verbose_name='نام گروه')),
                ('standard_name', models.CharField(max_length=300, verbose_name='نام استاندارد')),
                ('standard_name_latin', models.CharField(blank=True, max_length=300, null=True, verbose_name='نام استاندارد به لاتین')),
                ('old_standard_code', models.CharField(max_length=50, verbose_name='کد استاندارد قدیم')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه')),
                ('competency_code', models.PositiveIntegerField(default=0, verbose_name='کد شایستگی')),
                ('isco_job_code', models.PositiveIntegerField(verbose_name='کد شغل ISCO')),
                ('isco_group_code', models.PositiveIntegerField(verbose_name='کد گروه ISCO')),
                ('entry_education_level', models.CharField(max_length=200, verbose_name='سطح تحصیلات ورودی')),
                ('theoretical_hours', models.PositiveIntegerField(verbose_name='ساعت نظری')),
                ('practical_hours', models.PositiveIntegerField(verbose_name='ساعت عملی')),
                ('internship_hours', models.PositiveIntegerField(default=0, verbose_name='ساعت کارورزی')),
                ('project_hours', models.PositiveIntegerField(default=0, verbose_name='ساعت پروژه')),
                ('total_hours', models.PositiveIntegerField(verbose_name='ساعت کل')),
                ('work_and_knowledge', models.CharField(default='هیچ کدام', max_length=100, verbose_name='کارو دانش')),
                ('type', models.CharField(default='شغل', max_length=50, verbose_name='نوع')),
                ('compilation_date', models.DateField(verbose_name='تاریخ تدوین و به روز رسانی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='course.standards', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'استاندارد',
                'verbose_name_plural': 'استانداردها',
                'ordering': ['number'],
            },
        ),
    ]
