# Generated by Django 4.2.24 on 2025-09-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.standards', verbose_name='استاندارد'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='cluster',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='خوشه'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='competency_code',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='کد شایستگی'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='compilation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تدوین و به روز رسانی'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='entry_education_level',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سطح تحصیلات ورودی'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام گروه'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='internship_hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ساعت کارورزی'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='isco_group_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد گروه ISCO'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='isco_job_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد شغل ISCO'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='old_standard_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد استاندارد قدیم'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='practical_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ساعت عملی'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='project_hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ساعت پروژه'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='standard_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام استاندارد'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='theoretical_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ساعت نظری'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='total_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ساعت کل'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='type',
            field=models.CharField(blank=True, default='شغل', max_length=50, null=True, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='version',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='نسخه'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='work_and_knowledge',
            field=models.CharField(blank=True, default='هیچ کدام', max_length=100, null=True, verbose_name='کارو دانش'),
        ),
    ]
