# Generated by Django 5.1.3 on 2025-10-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_task_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes for answering the task', null=True),
        ),
    ]
