# Generated by Django 5.1.3 on 2025-11-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_task_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_page',
            field=models.BooleanField(default=False, help_text='اگر این گزینه رو انتخاب کنید، دسته بندی در صفحه اصلی نمایش داده خواهد باشد', verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
