# Generated by Django 5.2.1 on 2025-11-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_category_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('offline', 'آفلاین'), ('online', 'آنلاین'), ('pre_registration', 'پیش ثبت نام حضوری')], default='online', max_length=20, verbose_name='نوع دوره'),
        ),
    ]
