# Generated by Django 5.1.3 on 2025-11-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='اگر این گزینه را انتخاب کنید، دوره در بخش محبوب ترین نمایش داده خواهد شد', verbose_name='محبوب ترین'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_trending',
            field=models.BooleanField(default=False, help_text='اگر این گزینه را انتخاب کنید، دوره در بخش ترند نمایش داده خواهد شد', verbose_name='ترند'),
        ),
    ]
