# Generated by Django 5.1.3 on 2025-12-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_course_is_popular_course_is_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standards',
            name='entry_education_level',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='سطح تحصیلات ورودی'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='old_standard_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='کد استاندارد قدیم'),
        ),
        migrations.AlterField(
            model_name='standards',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='standards',
            name='type',
            field=models.CharField(blank=True, default='شغل', max_length=100, null=True, verbose_name='نوع'),
        ),
    ]
