# Generated by Django 5.1.3 on 2025-12-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_alter_standards_entry_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(blank=True, default=9999, help_text='عدد کمتر = اولویت بالاتر. دسته\u200cبندی\u200cها بر اساس این فیلد مرتب می\u200cشوند.', null=True, verbose_name='اولویت نمایش'),
        ),
    ]
