# Generated by Django 5.1.3 on 2025-12-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_category_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isco_code',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='کد ISCO تجمیعی'),
        ),
        migrations.AddField(
            model_name='category',
            name='old_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد قدیم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
