# Generated by Django 5.1.3 on 2025-12-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_category_isco_code_category_old_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, help_text='دوره فقط زمانی منتشر می\u200cشود که تایید شده باشد', verbose_name='منتشر شده'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='دوره باید توسط ادمین تایید شود تا منتشر شود', verbose_name='تایید شده'),
        ),
    ]
