# Generated by Django 5.1.3 on 2025-01-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_discount'),
        ('ticket', '0002_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.course'),
        ),
    ]
