# Generated by Django 5.1.3 on 2025-02-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organizerteacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
