# Generated by Django 5.1.3 on 2025-09-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_rolepermission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizerteacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizerteacher',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
