# Generated by Django 5.2.1 on 2025-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_organizer_is_active_organizer_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='organizer/documents'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='national_card',
            field=models.ImageField(blank=True, null=True, upload_to='organizer/documents'),
        ),
    ]
