# Generated by Django 5.2.1 on 2025-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_organizer_license_organizer_national_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('lastname', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('nationalcode', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('tel', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('career', models.CharField(blank=True, max_length=200, null=True, verbose_name='شغل')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'کاربر دستی',
                'verbose_name_plural': 'کاربران دستی',
                'ordering': ['-create_date'],
            },
        ),
    ]
