# Generated by Django 5.2.1 on 2025-11-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_manualuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='domain',
            field=models.CharField(blank=True, help_text='دامنه اختصاصی آموزشگاه (مثال: example.com)', max_length=255, null=True, verbose_name='دامنه'),
        ),
    ]
