# Generated by Django 5.2.1 on 2025-11-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_organizer_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='domain',
            field=models.CharField(blank=True, help_text='دامنه اختصاصی آموزشگاه (مثال: example.com) - بدون http:// یا https://', max_length=255, null=True, unique=True, verbose_name='دامنه'),
        ),
    ]
