# Generated by Django 5.2.1 on 2025-12-03 08:58

from django.db import migrations, models
import re


def migrate_domain_to_subdomain(apps, schema_editor):
    """
    تبدیل داده‌های domain موجود به subdomain
    """
    Organizer = apps.get_model('account', 'Organizer')
    
    for organizer in Organizer.objects.filter(domain__isnull=False):
        domain = organizer.domain.strip().lower() if organizer.domain else ''
        
        # حذف .onsho24.ir اگر وجود داشته باشد
        if domain.endswith('.onsho24.ir'):
            domain = domain[:-11]
        if domain == 'onsho24.ir':
            domain = ''
        
        # حذف کاراکترهای غیرمجاز
        domain = re.sub(r'[^a-z0-9_-]', '', domain)
        
        # تنظیم subdomain
        organizer.subdomain = domain.strip() if domain.strip() else None
        organizer.save()


def reverse_migrate_subdomain_to_domain(apps, schema_editor):
    """
    تبدیل subdomain به domain (برای rollback)
    """
    Organizer = apps.get_model('account', 'Organizer')
    
    for organizer in Organizer.objects.filter(subdomain__isnull=False):
        if organizer.subdomain:
            organizer.domain = organizer.subdomain
            organizer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_organizer_domain'),
    ]

    operations = [
        # ابتدا فیلد subdomain را اضافه می‌کنیم (nullable)
        migrations.AddField(
            model_name='organizer',
            name='subdomain',
            field=models.CharField(blank=True, help_text='زیردامنه اختصاصی آموزشگاه (مثال: sazman) - فقط نام subdomain بدون .onsho24.ir', max_length=100, null=True, verbose_name='زیردامنه'),
        ),
        # تبدیل داده‌های domain به subdomain
        migrations.RunPython(migrate_domain_to_subdomain, reverse_migrate_subdomain_to_domain),
        # حذف فیلد domain
        migrations.RemoveField(
            model_name='organizer',
            name='domain',
        ),
        # اضافه کردن unique constraint به subdomain
        migrations.AlterField(
            model_name='organizer',
            name='subdomain',
            field=models.CharField(blank=True, help_text='زیردامنه اختصاصی آموزشگاه (مثال: sazman) - فقط نام subdomain بدون .onsho24.ir', max_length=100, null=True, unique=True, verbose_name='زیردامنه'),
        ),
    ]
