# Generated by Django 5.2.1 on 2025-12-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_domain_to_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
