# Generated by Django 5.2.1 on 2025-12-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_organizer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='display_order',
            field=models.IntegerField(blank=True, default=9999, null=True, verbose_name='اولویت نمایش در صفحه اصلی'),
        ),
    ]
