from django.urls import path
from . import views

urlpatterns = [
    path('list', views.CourseListView.as_view(), name='course_list'),
    path('detail', views.CourseDetailView.as_view(), name='course_detail'),
    path('category/list', views.CategoryListView.as_view(), name='category_list'),
    path('category/home-page', views.HomePageCategoryListView.as_view(), name='home_page_category_list'),
    path('category/by-isco-code', views.CategoryByIscoCodeView.as_view(), name='category_by_isco_code'),
    path('trending', views.TrendingCoursesView.as_view(), name='trending_courses'),
    path('popular', views.PopularCoursesView.as_view(), name='popular_courses'),
    path('comment/add', views.AddCommentRateView.as_view(), name='comment_add'),
    path('attributes/list', views.AttributeListView.as_view(), name='attributes_list'),
    path('wishlist/create', views.CreateRemoveWishListView.as_view(), name='wishlist_create'),
    path('wishlist/list', views.ListWishListView.as_view(), name='wishlist_list'),
    path('task/create', views.CreateTaskView.as_view(), name='create-task'),
    path('task/course-lessons', views.TaskCourseLessonView.as_view(), name='task-course-lessons'),
    path('task/student-tasks', views.StudentTasksView.as_view(), name='student-tasks'),
    path('lesson/access-check', views.LessonAccessCheckView.as_view(), name='lesson-access-check'),
    path('task/teacher-submissions', views.TeacherTaskSubmissionsView.as_view(), name='teacher-task-submissions'),
    path('task/edit', views.EditTaskView.as_view(), name='update-task'),
    path('organization/create', views.OrganizerCreateView.as_view(), name='organization_create'),
    path('organization/edit', views.OrganizerUpdateView.as_view(), name='organizer_edit'),
    path('organization/detail', views.UserOrganizerDetailView.as_view(), name='user_organizer_detail'),
    path('organization/teachers/list', views.OrganizationTeachersListView.as_view(), name='organization_teachers_list'),
    path('organization/teachers/toggle', views.OrganizationTeacherToggleView.as_view(), name='organization_teacher_toggle'),
    path('organization/teachers/verify', views.OrganizationTeacherVerifyView.as_view(), name='organization_teacher_verify'),
    path('organization/teachers/add', views.OrganizationAddTeacherView.as_view(), name='organization_add_teacher'),
    path('organization/check-domain', views.CheckDomainView.as_view(), name='organization_check_domain'),
    path('modares/list', views.ModaresListView.as_view(), name='modares_list'),  # لیست دوره‌های مدرس
    path('mentor/list', views.MentorListAPIView.as_view(), name='mentor_list'),  # لیست منتورها
    path('create', views.CourseCreateView.as_view(), name='create_course'),
    path('update', views.UpdateCourseAPI.as_view(), name='update_course'),
    path('chapter/create', views.ChapterCreateView.as_view(), name='create_chapter'),
    path('chapter/update', views.ChapterUpdateView.as_view(), name='update_chapter'),
    path('lesson/create', views.LessonCreateView.as_view(), name='create_lesson'),
    path('lesson/update', views.UpdateLessonAPI.as_view(), name='update_lesson'),
    path('user/list', views.UserCoursesListView.as_view(), name='course_user_list'),
    path('user/enrolled/list', views.UserEnrolledCoursesListView.as_view(), name='course_user_enrolled_list'),
    path('user/detail', views.TeacherCourseDetailView.as_view(), name='teacher_course_detail'),
    path('user/task/list', views.UserTasksListView.as_view(), name='task_user_list'),
    path('organization/list', views.OrganizerListView.as_view(), name='organizer_list'),
    path('organization/by-slug', views.OrganizerBySlugView.as_view(), name='organizer_by_slug'),
    path('task/answer/create', views.TaskAnswerView.as_view(), name='task_answer'),
    path('task/detail', views.TaskDetailAPIView.as_view(), name='task_detail'),
    path('task/answer/list', views.AnswerListAPIView.as_view(), name='answer_list'),
    path('task/answer/detail', views.AnswerDetailAPIView.as_view(), name='answer_detail'),
    path('task/answer/changestatus', views.UpdateTaskAnswerStatusAPIView.as_view(), name='task_answer_changestatus'),
    
    # Standards URLs
    path('standards/list', views.StandardsListView.as_view(), name='standards_list'),
    path('standards/tree', views.StandardsTreeView.as_view(), name='standards_tree'),
    path('standards/detail', views.StandardsDetailView.as_view(), name='standards_detail'),
    path('standards/create', views.StandardsCreateView.as_view(), name='standards_create'),
    path('standards/update', views.StandardsUpdateView.as_view(), name='standards_update'),
    path('standards/delete', views.StandardsDeleteView.as_view(), name='standards_delete'),
    path('standards/children', views.StandardsChildrenView.as_view(), name='standards_children'),
    path('standards/ancestors', views.StandardsAncestorsView.as_view(), name='standards_ancestors'),
    path('standards/siblings', views.StandardsSiblingsView.as_view(), name='standards_siblings'),
    path('standards/filter-options', views.StandardsFilterOptionsView.as_view(), name='standards_filter_options'),
    path('standards/for-course', views.StandardsForCourseView.as_view(), name='standards_for_course'),
    path('task/answer/statuses', views.AnswerStatusListView.as_view(), name='answer_statuses'),
    path('courses/by-old-standard-code', views.CoursesByOldStandardCodeView.as_view(), name='courses_by_old_standard_code'),
    path('search', views.SearchView.as_view(), name='search'),
    path('old-standard-code/suggest', views.OldStandardCodeSuggestView.as_view(), name='old_standard_code_suggest'),
]
