# Generated by Django 5.1.3 on 2025-11-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'محتوای استاتیک',
                'verbose_name_plural': 'محتوای استاتیک',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('external', models.BooleanField(default=False, verbose_name='لینک خارجی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('static_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='static_content.staticcontent', verbose_name='محتوای استاتیک')),
            ],
            options={
                'verbose_name': 'لینک مرتبط',
                'verbose_name_plural': 'لینک\u200cهای مرتبط',
                'ordering': ['order', 'create_date'],
            },
        ),
    ]
