# Generated by Django 5.1.3 on 2025-11-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0002_alter_staticcontent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticcontent',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
