# Generated by Django 5.2.1 on 2025-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0003_alter_staticcontent_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticcontent',
            options={'ordering': ['category', 'display_order', '-create_date'], 'verbose_name': 'محتوای استاتیک', 'verbose_name_plural': 'محتوای استاتیک'},
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='category',
            field=models.CharField(choices=[('skills', 'مهارت ها'), ('programs', 'برنامه ها'), ('industries', 'صنایع و حرفه ها'), ('centers', 'مراکز تخصصی'), ('learners', 'مهارت\u200cآموزان'), ('institutes', 'آموزشگاه\u200cها'), ('onsho', 'آن\u200cشو')], default='onsho', max_length=50, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
