# Generated by Django 5.1.3 on 2025-12-10 17:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0004_alter_staticcontent_options_staticcontent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticcontent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='staticcontent',
            name='short_description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات کوتاه'),
        ),
    ]
