# Generated by Django 5.1.3 on 2025-01-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان وبینار')),
                ('description', models.TextField(verbose_name='توضیحات وبینار')),
                ('speaker', models.CharField(max_length=255, verbose_name='سخنران')),
                ('date', models.DateField(verbose_name='تاریخ وبینار')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='webinars/', verbose_name='تصویر وبینار')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'وبینار',
                'verbose_name_plural': 'وبینارها',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='WebinarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سرفصل')),
                ('content', models.TextField(verbose_name='محتوای سرفصل')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='webinar.webinar', verbose_name='وبینار')),
            ],
            options={
                'verbose_name': 'سرفصل وبینار',
                'verbose_name_plural': 'سرفصل\u200cهای وبینار',
            },
        ),
    ]
