# Generated by Django 5.1.3 on 2025-01-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='date',
            field=models.DateTimeField(verbose_name='تاریخ وبینار'),
        ),
    ]
