# Generated by Django 5.1.3 on 2025-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_alter_webinar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='date',
            field=models.DateField(verbose_name='تاریخ وبینار'),
        ),
    ]
