# Generated by Django 5.1.3 on 2025-01-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_alter_webinar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='date',
            field=models.CharField(max_length=150, verbose_name='تاریخ وبینار'),
        ),
    ]
