# Generated by Django 5.1.3 on 2025-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0004_alter_webinar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
    ]
