# Generated by Django 5.2.1 on 2025-11-19 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_organizer_license_organizer_national_card'),
        ('course', '0030_course_type'),
        ('payment', '0004_paymentgateway_transaction_authority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_credits', models.PositiveIntegerField(default=1, help_text='Total number of uses available')),
                ('remaining_credits', models.PositiveIntegerField(default=1, help_text='Remaining number of uses')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_codes', to='course.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_codes', to='account.organizer')),
                ('purchased_by', models.ForeignKey(help_text='The organization user who purchased this code', on_delete=django.db.models.deletion.CASCADE, related_name='purchased_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='CodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_redemptions', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_redemptions', to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='payment.purchasecode')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchasecode',
            index=models.Index(fields=['code'], name='payment_pur_code_9e82ef_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasecode',
            index=models.Index(fields=['organization', 'is_active'], name='payment_pur_organiz_40be41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coderedemption',
            unique_together={('code', 'user', 'course')},
        ),
    ]
